### ISSUE TITLE
Board horizontal scroll add shadows

### ISSUE THREAD

**Issue by Cannonb4ll** [ploi-deploy/roadmap#33]
To indicate that there's more content to the right to scroll too.

```css
.scroll-shadows {
  background-image: /* Shadows */
          linear-gradient(to right, rgba(249 250 251), rgba(249 250 251)),
          linear-gradient(to right, rgba(249 250 251), rgba(249 250 251)),
            /* Shadow covers */
          linear-gradient(to right, rgba(0, 0, 0, .25), rgba(255, 255, 255, 0)),
          linear-gradient(to left, rgba(0, 0, 0, .25), rgba(255, 255, 255, 0));

  background-position: left center, right center, left center, right center;
  background-repeat: no-repeat;
  background-size: 20px 100%, 20px 100%, 10px 100%, 10px 100%;

  /* Opera doesn't support this in the shorthand */
  background-attachment: local, local, scroll, scroll;
}
```
